#! /bin/bash
shopt -s nocasematch
#turn off case sensitivity
read -p "color or mono?: " REPLY
if [[ $REPLY =~ colou?r ]];then
    source $HOME/snippets/colors
    exit 0
fi
shopt -u nocasematch

echo "Your option is $REPLY"
exit 1
